name: windows-exe
on:
  push:
    paths:
      - 'native/windows/**'
      - '.github/workflows/windows-exe.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure (CMake)
        run: cmake -S native/windows -B build -A x64
      - name: Build (Release)
        run: cmake --build build --config Release --verbose
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: pistream-exe-beta
          path: |
            build/Release/*.exe
            build/*.exe
